### ISSUE TITLE
链式调用问题

### ISSUE THREAD

**Issue by lg430** [goal-web/goal#2]
https://github.com/goal-web/goal/blob/91ff6a459e89bc4a993d95503a03976fd3c8bcd2/app/dao/user.go#L6

find返回nil的情况下, 后面的类型断言.(models.User)会panic吧?

**Comment by qbhy** [comment]
有第二个参数的情况下，不会panic

**Comment by qbhy** [comment]
@lg430 有两个返回值的情况下，如果断言失败，第二个值会是 false ，从而可以避免 panic
